# 아래의 설정이 local 일 경우에만,ItemServiceApplication에서 TestDataInit을 등록해서 초기 테스트 데이터를 등록함
spring.profiles.active=local

spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa

#jdbcTemplate sql log
logging.level.org.springframework.jdbc=debug